# Generated by Django 3.0.7 on 2020-07-03 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Management', '0006_auto_20200703_2205'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='assignment_solution',
            field=models.TextField(blank=True, null=True),
        ),
    ]
